# SENTENCE RANKING
# @author: Takao Kakegawa

import nltk
from nltk.corpus import stopwords
import re
import spacy
import pytextrank

# Load in stopwords from nltk package
stop_words = stopwords.words('english')
# Load in spacy package
nlp = spacy.load("en_core_web_sm")
nlp.add_pipe("textrank")

def textrank_sentences(texts, phrase_lim=10, sentence_lim=5):
  '''
    @type texts: str
    @param content text 
    @type phrase_lim: int
    @param phrase token limit length for ranking scheme
    @type phrase_lim: int
    @param phrase token limit length for ranking scheme
    @type sentence_lim: int
    @param sentence limit for output
    @rtype summary: string 
    @rparam output summary generated by Facebook-BART-CNN 
    '''
  # returns a list of top sentence_lim sentences associated with the top phrase_lim phrases from textrank.
  doc = nlp(texts)
  tr = doc._.textrank
  output = [sent.text for sent in tr.summary(limit_phrases=phrase_lim, limit_sentences=sentence_lim)]
  return output
